spring.application.name=demo

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/lab7demo
spring.datasource.username=postgres
spring.datasource.password=admin123

# JPA / Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect